### ISSUE TITLE
tandem_run_managerの使い方

### ISSUE THREAD

**Issue by shunsugar** [KBKN-Autonomous-Robotics-Lab/orange_navigation#20]
> 上記のウェイポイントファイルの場合、tandem_start パラメータをもつ1つめのウェイポイントに到達後、2つめに向かい始めるときに縦列対策が有効になります。このとき、パラメータ "switch_costmaps" で指定した costmap は無効化されます。レーザースキャンデータのうち、正面から "use_angle" で指定した角度の中に、"danger_dist" で指定した距離以内の障害物があればナビゲーションを中断します。中断後も観測し続け、障害物が離れればナビゲーションを再開します。そして、tandem_end パラメータをもつ3つめのウェイポイントに到達したら縦列対策を有効にする前の状態に戻ります。
なお、パラメータ tandem_start, tandem_end に対する数値は意味をもちませんが、縦列対策を有効にしたい区間が複数ある場合、セットで同じ数値を指定しておくと分かりやすいかもしれません。

Wikiの説明を読んでいて思ったのですが、縦列対策が有効になるのはtandem_startパラメータを持つwaypointに到達後から、tandem_endパラメータを持つwaypointに到達するまでの間ですか？

例えば下のような場合、waypoint No.5からNo.8まで縦列対策が有効になるということですか？

waypoints:
- point: {x: 1.0, y: 0.0, z: 0.0, vel: 1.0, rad: 0.8, stop: false}
- point: {x: 2.0, y: 0.0, z: 0.0, vel: 1.0, rad: 0.8, stop: false}
- point: {x: 3.0, y: 0.0, z: 0.0, vel: 1.0, rad: 0.8, stop: false}
- point: {x: 4.0, y: 0.0, z: 0.0, vel: 1.0, rad: 0.8, stop: false, tandem_start: 1}
- point: {x: 5.0, y: 0.0, z: 0.0, vel: 1.0, rad: 0.8, stop: false}                             ## 縦列対策: 有効
- point: {x: 6.0, y: 0.0, z: 0.0, vel: 1.0, rad: 0.8, stop: false}                             ## 縦列対策: 有効
- point: {x: 7.0, y: 0.0, z: 0.0, vel: 1.0, rad: 0.8, stop: false}                             ## 縦列対策: 有効
- point: {x: 8.0, y: 0.0, z: 0.0, vel: 1.0, rad: 0.8, stop: false, tandem_end: 1}   ## 縦列対策: 有効
- point: {x: 9.0, y: 0.0, z: 0.0, vel: 1.0, rad: 0.8, stop: false}
- point: {x: 10.0, y: 0.0, z: 0.0, vel: 1.0, rad: 0.8, stop: false}
- point: {x: 11.0, y: 0.0, z: 0.0, vel: 1.0, rad: 0.8, stop: false}
- point: {x: 12.0, y: 0.0, z: 0.0, vel: 1.0, rad: 0.8, stop: false, tandem_start: 2}
...
finish_pose:
  header: {seq: 0, stamp: 113.132, frame_id: map}
  pose:
    position: {x: 4.0, y: 0.0, z: 0.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}

> そして、tandem_end パラメータをもつ3つめのウェイポイントに到達したら縦列対策を有効にする前の状態に戻ります。

ここら辺がよくわからなかったので質問させていただきます。
@koki0624

**Comment by koki0624** [comment]
その通りです。

**Comment by shunsugar** [comment]
ありがとうございます。
